---
- name: check epel repository
  become: yes
  yum:
    pkg: epel-release
    state: present
  tags:
    - openconnect

- name: install openconnect
  become: yes
  yum:
    pkg: ocserv
    state: installed
  tags:
    - openconnect

- name: copy systemd unit file
  become: yes
  template:
    src: ocserv.service.j2
    dest: /usr/lib/systemd/system/ocserv.service
    owner: root
    group: root
  tags:
    - openconnect
